"""Tests for scripts/render_board.py — the v2 visual perception render pipeline.

Contract: contracts/v2-stage-1-foundation.contract.md, Batch 1.1.

Each test maps to one Batch Completion Criteria checklist item:
  - test_render_returns_expected_dict_shape  → "return dict shape" criterion
  - test_pngs_are_nonzero                    → "PNGs non-zero" criterion
  - test_dark_background_present             → "#1a1a1a BG sample pixel" criterion
  - test_render_under_2_seconds              → "<2 s timeout" criterion (pytest-timeout)
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Make scripts/ importable as a flat module
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from render_board import render_board  # noqa: E402

BOARD_FILE = PROJECT_ROOT / "baselines" / "4.6" / "blue_pill.kicad_pcb"


@pytest.fixture(scope="module")
def rendered(tmp_path_factory) -> dict[str, Path]:
    """Render the blue_pill board once per module, share results across tests."""
    if not BOARD_FILE.exists():
        pytest.skip(f"Reference board not present: {BOARD_FILE}")
    out_dir = tmp_path_factory.mktemp("renders")
    return render_board(BOARD_FILE, output_dir=out_dir)


def test_render_returns_expected_dict_shape(rendered: dict[str, Path]) -> None:
    """Contract: returned dict has 'full', 'copper', 'svg' keys; full+copper are
    existing PNGs; svg is the intermediate SVG file."""
    assert set(rendered.keys()) == {"full", "copper", "svg"}, (
        f"Unexpected keys: {sorted(rendered.keys())}"
    )
    assert rendered["full"].exists(), f"Full PNG missing: {rendered['full']}"
    assert rendered["copper"] is not None, "Copper variant should be generated by default"
    assert rendered["copper"].exists(), f"Copper PNG missing: {rendered['copper']}"
    assert rendered["svg"].exists(), f"SVG missing: {rendered['svg']}"
    assert rendered["full"].suffix == ".png"
    assert rendered["copper"].suffix == ".png"
    assert rendered["svg"].suffix == ".svg"


def test_pngs_are_nonzero(rendered: dict[str, Path]) -> None:
    """Contract: both PNG files have size > 0 (rasterization succeeded)."""
    assert rendered["full"].stat().st_size > 0, "Full PNG is empty"
    assert rendered["copper"].stat().st_size > 0, "Copper PNG is empty"


def test_dark_background_present(rendered: dict[str, Path]) -> None:
    """Contract: pixel at (10, 10) of the full PNG is dark BG #1a1a1a (26,26,26)
    with ±2 tolerance per channel (anti-aliasing slack)."""
    from PIL import Image

    with Image.open(rendered["full"]) as img:
        img_rgb = img.convert("RGB")
        pixel = img_rgb.getpixel((10, 10))
    assert pixel is not None, "Failed to sample pixel (10, 10)"
    r, g, b = pixel[0], pixel[1], pixel[2]
    expected = 26
    tolerance = 2
    assert abs(r - expected) <= tolerance, f"R channel {r}, expected ~{expected}"
    assert abs(g - expected) <= tolerance, f"G channel {g}, expected ~{expected}"
    assert abs(b - expected) <= tolerance, f"B channel {b}, expected ~{expected}"


@pytest.mark.timeout(2)
def test_render_under_2_seconds(tmp_path: Path) -> None:
    """Contract: render_board on blue_pill.kicad_pcb completes within 2 seconds wall.

    Enforced via pytest-timeout. Uses a fresh tmp_path (not the module fixture) so
    timing reflects a cold call, not a cached result.
    """
    if not BOARD_FILE.exists():
        pytest.skip(f"Reference board not present: {BOARD_FILE}")
    result = render_board(BOARD_FILE, output_dir=tmp_path)
    assert result["full"].exists()
